"""users.login not unique

Revision ID: 57921e29effc
Revises: d542225dc25e
Create Date: 2025-11-16 17:10:10.631235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57921e29effc'
down_revision: Union[str, None] = 'd542225dc25e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_login_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_login_key'), 'users', ['login'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
