"""users.second_name delete col

Revision ID: d542225dc25e
Revises: c587983b53ff
Create Date: 2025-11-15 21:11:06.738503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd542225dc25e'
down_revision: Union[str, None] = 'c587983b53ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'second_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('second_name', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
